version: '3'

services:
        django:
                build: .
                ports:
                        - "8000:8000"
        redis:
                image: redis
                ports:
                         - "6379:6379"
                volumes: 
                        - /opt/docker/redis/etc:/usr/local/etc/redis

                command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

