version: '3'

services:
        app:
                build:
                        context: ./

                ports:
                        - 8000:8000

                command: >
                        sh -c "python3 manage.py migrate &&
                               python3 manage.py runserver 185.251.90.37:8000"
                
