
---
- name: django + redis + docker container
  hosts: localhost
  become: yes



  vars:
      
      redis_service: /root/django-project/redis.service
      redis_slave: /root/django-project/redis-slave.conf
     
  tasks:
     
       - name: Install PIP
         apt:
            pkg:
                - python3-pip

#       - name: Install Redis
#         apt: name=redis-server state=latest

#       - name: create redis systemd file
#         copy: src={{ redis_service }} dest=/etc/systemd/system/redis.service mode=0644

#       - name: create redis replica
#         copy: src={{ redis_slave }} dest=/etc/redis mode=0644

       - name: Check configs
         replace:
                 path: "/etc/redis/redis.conf"
                 regexp: '^bind 127.0.0.1 ::1$'
                 replace: 'bind 0.0.0.0'
         notify:
                 - Restart redis


       - name: Check configs_2
         replace:
                 path: "/etc/redis/redis.conf"
                 regexp: '^supervised no$'
                 replace: 'supervised systemd'
         notify:
                 - Restart Redis


       - name: Install Docker
         apt: name={{ item }} state=latest update_cache=yes
         loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
       - name: Add Docker GPG apt Key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
       - name: Add Docker Repository
         apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
       - name: Update apt and install docker-ce
         apt: update_cache=yes name=docker-ce state=latest
       - name: Install Docker Module for Python
         pip:
            name: docker

         
       - name: Build Docker Image
         community.docker.docker_image:
            name: new2
            build:
               path: /root/newproject/django-project/.
            source: build
         
         
       - name: Run Docker Container
         community.docker.docker_container:
             name: django_container
             image: new2
             ports:
                   - "8000:8000"
                   - "6378:6379"

         
                  
            
               

