---

- name: django + redis + docker container
  hosts: localhost
  become: yes



  vars:
      
      redis_slave: /root/django-project/redis-slave.conf
      
  
  tasks:
       - name: Update Apt
         apt:
             update_cache: yes
        
       - name: Change Django Allowed Hosts
         lineinfile:
                dest: /root/django-project/django_redis_demo/django_redis_demo/settings.py
                regexp: '^ALLOWED_HOSTS'
                line: 'ALLOWED_HOSTS = {{ ansible_all_ipv4_addresses }}'
 
       - name: Install PIP
         apt:
            pkg:
                - python3-pip

       - name: Install Redis
         apt:
             name: redis-server
             state: latest


       - name: change redis systemd file
         lineinfile:
                 dest: /etc/systemd/system/redis.service
                 regexp: '^ExecStart'
                 line: 'ExecStart=/usr/bin/redis-server /etc/redis/redis%i.conf'

       - name: change redis systemd file
         lineinfile:
                 dest: /etc/systemd/system/redis.service
                 regexp: '^PIDFile'
                 line: 'PIDFile=/var/run/redis%i/redis-server.pid'

       - name: change redis systemd file
         lineinfile:
                 dest: /etc/systemd/system/redis.service
                 regexp: '^RuntimeDirectory'
                 line: 'RuntimeDirectory=redis%i'

       - name: change redis systemd file
         lineinfile:
                 dest: /etc/systemd/system/redis.service
                 regexp: '^ReadWritePaths'
                 line: 'ReadWritePaths=-/var/run/redis%i'

       - name: change redis systemd file
         lineinfile:
                 dest: /etc/systemd/system/redis.service
                 regexp: '^Description'
                 line: 'Description=Advanced key-value store (%I)'


       - name: create redis replica
         copy: src={{ redis_slave }} dest=/etc/redis owner=redis group=redis mode=0644

       - name: Bind redis to 0.0.0.0
         lineinfile:
                 dest: /etc/redis/redis.conf
                 regexp: '^bind 127.0.0.1 ::1$'
                 line: 'bind 0.0.0.0'
         notify:
                       - Restart Redis

       - name: change redis configs
         lineinfile:
                 dest: /etc/redis/redis.conf
                 regexp: '^supervised no$'
                 line: 'supervised systemd'

         notify:
                       - Restart Redis


       - name: "Redis systemd restart"
         systemd:
                 daemon_reload: true


       - name: Install Docker
         apt: name={{ item }} state=latest update_cache=yes
         loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
       - name: Add Docker GPG apt Key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
       - name: Add Docker Repository
         apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
       - name: Update apt and install docker-ce
         apt: update_cache=yes name=docker-ce state=latest
       - name: Install Docker Module for Python
         pip:
            name: docker

         
       - name: Build Docker Image
         community.docker.docker_image:
            name: new2
            build:
               path: /root/django-project/.
            source: build
         
         
       - name: Run Docker Container
         community.docker.docker_container:
             name: django_container
             image: new2
             ports:
                   - "8000:8000"
                   
  handlers:
        - name: Restart Redis
          systemd:
             name: redis-server
             state: restarted

                  
            
               

