---

- name: django + redis + docker container
  hosts: localhost
  become: yes

  vars:
      
      redis_slave: /root/django-project/redis-slave.conf
      redis_server_conf: redis%i
      redis_bind: 0.0.0.0
      systemd_yes: systemd
      description: (%I)
      cpquota: CPUQuota=10%


  tasks:
        
       - name: Change Django Allowed Hosts
         template:
                 src: /root/django-project/django_settings_template.j2
                 dest: /root/django-project/django_redis_demo/django_redis_demo/settings.py
 
       - name: Install PIP
         apt:
            pkg:
                - python3-pip

       - name: Install Redis
         apt:
             name: redis-server
             state: latest


       - name: change redis systemd file
         template:
                  src: /root/django-project/redis_service_template.j2
                  dest: /etc/systemd/system/redis.service 
       
       - name: Set CPUQuota for Redis
         template:
                  src: /root/django-project/redis_service_template.j2
                  dest: /etc/systemd/system/redis.service

       - name: create redis replica
         copy: src={{ redis_slave }} dest=/etc/redis owner=redis group=redis mode=0644

       - name: change redis conf file
         template:
                  src: /root/django-project/redis_conf_template.j2
                  dest: /etc/redis/redis.conf

         notify:
                       - Restart Redis


       - name: Redis systemd restart
         systemd:
                 daemon_reload: true


       - name: Install Docker
         apt:
             pkg: 
                - apt-transport-https
                - ca-certificates
                - curl 
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools

       - name: Add Docker GPG apt Key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

       - name: Add Docker Repository
         apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present

       - name: Update apt and install docker-ce
         apt: update_cache=yes name=docker-ce state=latest

       - name: Install Docker Module for Python
         pip:
            name: docker

       - name: Build Docker Image
         community.docker.docker_image:
            name: new2
            build:
               path: /root/django-project/.
            source: build
         
         notify:
                 - Rebuild Docker Image

       - name: Run Docker Container
         community.docker.docker_container:
             name: new_container
             image: new2
             ports:
                   - "8000:8000"
                   
  handlers:
        - name: Restart Redis
          systemd:
             name: redis-server
             state: restarted

                  
        - name: Rebuild Docker Image
          community.docker.docker_image:
            name: new2
            build:
               path: /root/django-project/.
            source: build    
               

