
---
- name: django + redis + docker container
  hosts: all
  become: yes



  vars:
      
      source_file: /root/newproject/django-project
      destin_file: /root
      project_path: /root/django-project
      redis_service: /root/newproject/django-project/redis.service
      redis_slave: /root/newproject/django-project/redis-slave.conf
     
  tasks:
       - name: Copy Django app
         copy: src={{ source_file }} dest={{ destin_file }} mode=0755
      

       - name: Install PIP
         apt:
            pkg:
                - python3-pip

       - name: Install Redis
         apt: name=redis-server state=latest

       - name: create redis replica
         copy: src={{ redis_service }} dest=/etc/systemd/system mode=0755
         copy: src={{ redis_slave }} dest=/etc/redis mode=0755

       - name: Install Docker
         apt: name={{ item }} state=latest update_cache=yes
         loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
       - name: Add Docker GPG apt Key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
       - name: Add Docker Repository
         apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
       - name: Update apt and install docker-ce
         apt: update_cache=yes name=docker-ce state=latest
       - name: Install Docker Module for Python
         pip:
            name: docker

         
       - name: Build Docker Image
         community.docker.docker_image:
            name: new2
            build:
               path:/root/django-project
            source: build
         
         
       - name: Run Docker Container
         community.docker.docker_container:
             name: django_container
             image: new2
             ports:
                   - "8000:8000"
                   - "6378:6379"

         
                  
            
               

