
---
- name: django + redis + docker container
  hosts: localhost
  become: yes



  vars:
      
      redis_service: /root/django-project/redis.service
      redis_slave: /root/django-project/redis-slave.conf
     
  tasks:
     
       - name: Install PIP
         apt:
            pkg:
                - python3-pip

       - name: Install Redis
         apt: name=redis-server state=latest

       - name: create redis systemd file
         replace:
                 path: "/etc/systemd/system/redis.service"
                 regexp: '^redis.conf$'
                 replace: 'redis%i.conf'

       - name: fixed redis systemd file
         replace:
                 path: "/etc/systemd/system/redis.service"
                 regexp: '^/var/run/redis$'
                 replace: '/var/run/redis%i'

       - name: create redis replica
         copy: src={{ redis_slave }} dest=/etc/redis owner=redis group=redis mode=0644

       - name: Check configs
         replace:
                 path: "/etc/redis/redis.conf"
                 regexp: '^bind 127.0.0.1 ::1$'
                 replace: 'bind 0.0.0.0'

       - name: check configs_2
         replace:
                 path: "/etc/redis/redis.conf"
                 regexp: '^supervised no$'
                 replace: 'supervised systemd'

        
         notify: Redis Restart

       - name: "Redis systemd restart"
         systemd:
                 daemon_reload: true


       - name: Install Docker
         apt: name={{ item }} state=latest update_cache=yes
         loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
       - name: Add Docker GPG apt Key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
       - name: Add Docker Repository
         apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
       - name: Update apt and install docker-ce
         apt: update_cache=yes name=docker-ce state=latest
       - name: Install Docker Module for Python
         pip:
            name: docker

         
       - name: Build Docker Image
         community.docker.docker_image:
            name: new2
            build:
               path: /root/django-project/.
            source: build
         
         
       - name: Run Docker Container
         community.docker.docker_container:
             name: django_container
             image: new2
             ports:
                   - "8000:8000"
                   


                  
            
               

